#!/bin/sh
### BEGIN INIT INFO
# Provides:          xmlplus
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop xmlplus server
### END INIT INFO

ROOT=/root/xmlplus
DEAMON=$ROOT/xmlplus.js
LOG=$ROOT/xmlplus.log
PID=$ROOT/xmlplus.pid

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
 start)
  forever start -l $LOG --pidFile $PID -a $DEAMON
  ;;
 stop)
  forever stop --pidFile $PID $DEAMON
  ;;
 restart)
  forever restart -l $LOG --pidFile $PID -a $DEAMON
  ;;
  *)
  echo "Usage: /etc.init.d/xmlplus {start|stop|restart}"
  exit 1
  ;;
esac
